-- Insertar productos de ejemplo
INSERT INTO Producto (Codigo, Disponible, Nombre, Precio, Imagen, Logo, Descripcion, Categoria, Desc_Principal, Desc_Otros, Descuento, Disclaimer)
VALUES 
('8039-ALE-0818', 1, 'Adaptessens', 15.99, 'assets/productos/adaptessens.png', 'assets/logos/adaptessens.png', 'Es un producto de soporte nutricional cuyo propósito es adicionar a la dieta normal, siendo fuente concentrada de nutrientes y otras sustancias con efecto fisiológico o nutricional.', 'Concentración', 'Este producto está diseñado para mejorar la concentración y el enfoque mental. Contiene ingredientes naturales que ayudan a mantener la claridad mental durante períodos prolongados de actividad intelectual.', 'Modo de uso: Tomar 1 cápsula al día con las comidas.\nContenido: 60 cápsulas.\nPrecauciones: No exceder la dosis recomendada. Consultar con un médico si está embarazada o en período de lactancia.', 50, 'El producto no es adecuado para ser consumido como única fuente de alimento. No supera la dosis recomendada.'),
('ECCMS002', 1, 'Calmessens', 10.99, 'assets/productos/calmessens.png', 'assets/logos/calmessens.png', 'Fórmula con Colina, Vitamina B1, Niacina, Ácido Pantoténico y Manganeso. Es un producto de soporte nutricional cuyo propósito es adicionar a la dieta normal, siendo fuente concentrada de nutrientes y otras sustancias con efecto fisiológico o nutricional.', 'Calmantes', 'Diseñado para reducir el estrés y la ansiedad, promoviendo un estado de calma y relajación. Contiene ingredientes que actúan sobre el sistema nervioso central para mejorar el bienestar emocional.', 'Modo de uso: Tomar 2 cápsulas al día, preferiblemente por la mañana y por la noche.\nContenido: 90 cápsulas.\nPrecauciones: No usar en menores de 12 años. Consultar con un médico si está tomando otros medicamentos.', 10, 'El producto no es adecuado para ser consumido como única fuente de alimento. No supera la dosis recomendada.'),
('ECCLS001', 1, 'Colessens', 9.99, 'assets/productos/colessens.png', 'assets/logos/colessens.png', 'Fórmula con Bergamota, Ajo, Corteza de Pino, Saccharum officinarum, Magnesio y Vitaminas esenciales. Es un producto de soporte nutricional cuyo propósito es adicionar a la dieta normal, siendo fuente concentrada de nutrientes y otras sustancias con efecto fisiológico o nutricional.', 'Concentración', 'Mejora la circulación cerebral y la memoria. Contiene antioxidantes que protegen las células cerebrales y mejoran la función cognitiva.', 'Modo de uso: Tomar 1 cápsula dos veces al día.\nContenido: 60 cápsulas.\nPrecauciones: Evitar en caso de alergia a cítricos. Consultar con médico si tiene problemas de coagulación.', 0, 'El producto no es adecuado para ser consumido como única fuente de alimento. No supera la dosis recomendada.'),
('ECCRS002', 1, 'Coraessens', 7.99, 'assets/productos/coraessens.png', 'assets/logos/coraessens.png', 'Fórmula con Corazón Bovino liofilizado, Magnesio, Metilcobalamina, Piridoxal-5-Fosfato y L-5 Metiltetrahidrofolato. Es un producto de soporte nutricional cuyo propósito es adicionar a la dieta normal, siendo fuente concentrada de nutrientes y otras sustancias con efecto fisiológico o nutricional.', 'Calmantes', 'Favorece la salud cardiovascular y reduce la fatiga mental. Contiene nutrientes esenciales para el funcionamiento óptimo del corazón y el cerebro.', 'Modo de uso: Tomar 1 cápsula al día por la mañana.\nContenido: 30 cápsulas.\nPrecauciones: No usar si es alérgico a productos bovinos. Consultar con médico si tiene problemas cardíacos.', 0, 'El producto no es adecuado para ser consumido como única fuente de alimento. No supera la dosis recomendada.'),
('ECCURCE001', 1, 'Curcetin', 5.55, 'assets/productos/curcetin.png', 'assets/logos/curcetin.png', 'Fórmula con Magnesio, Vitamina C, Curcuma longa l y Quercitina. Es un producto de soporte nutricional cuyo propósito es adicionar a la dieta normal, siendo fuente concentrada de nutrientes y otras sustancias con efecto fisiológico o nutricional.', 'Concentración', 'Combate la inflamación y mejora la función cognitiva. Contiene curcumina, un potente antiinflamatorio natural que ayuda a proteger el cerebro.', 'Modo de uso: Tomar 2 cápsulas al día con alimentos.\nContenido: 120 cápsulas.\nPrecauciones: Puede causar malestar estomacal en personas sensibles.', 0, 'El producto no es adecuado para ser consumido como única fuente de alimento. No supera la dosis recomendada.'),
('ECLCH006', 1, 'Lechuguin', 6.55, 'https://cloudfront-us-east-1.images.arcpublishing.com/semana/3REV53527RABTL2YCEI3KJZWAM.jpg', 'assets/logos/vegezym.png', 'Es una lechuga, realmente no hay mucha ciencia detrás de ella.', 'Concentración', 'Literalmente es una lechuga.', 'Modo de uso: En la cocina, supongo.\nContenido: Una lechuga.\nPrecauciones: No dejar usar maquinaria pesada a la Lechuga.', 69, 'El producto no es adecuado para ser consumido como única fuente de alimento. No supera la dosis recomendada.'),
('ECEJM009', 1, 'Ejemplo', 0.99, 'assets/productos/imgtest.jpg', 'assets/logos/curcetin.png', 'Descripción de ejemplo.', 'Calmantes', 'Descripcion principal.', 'Otros.', 0, 'El producto no es adecuado para ser consumido como única fuente de alimento. No supera la dosis recomendada.');

-- Insertar relaciones de productos promocionados
INSERT INTO ProductoPromocionado (ProductoId, PromocionadoId)
VALUES 
(1, 2), (1, 3), (1, 5),
(2, 1), (2, 4), (2, 6),
(3, 1), (3, 5), (3, 6),
(4, 2), (4, 5), (4, 6),
(5, 1), (5, 3), (5, 4),
(6, 2), (6, 3), (6, 4),
(7, 6), (7, 7), (7, 1);