ALTER TABLE Usuario 
ADD Activo BIT NOT NULL DEFAULT 1;    

ALTER TABLE Fondo
ADD Activo BIT NOT NULL DEFAULT 1,
    CreadoEl DATETIME2 DEFAULT GETDATE(), 
    ActualizadoEl DATETIME2 DEFAULT GETDATE();

ALTER TABLE Alineacion
ADD Activo BIT NOT NULL DEFAULT 1,
    CreadoEl DATETIME2 DEFAULT GETDATE(),
    ActualizadoEl DATETIME2 DEFAULT GETDATE();

